version: '3'

services:
#  db:
#    image: postgres:13
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres
#      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-vol:/var/lib/postgresql/data/

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
        - "6379:6379"
    volumes:
        - redis-vol:/data

volumes:
  postgres-vol: null
  redis-vol: null